### ISSUE TITLE
When i train with your config,i encounter a problem

### ISSUE THREAD

**Issue by EwardJohn** [cizhenshi/TianchiGuangdong2019_2th#13]
When i train with your config,i encounter a problem,it is :
Traceback (most recent call last):
  File "src/tools/train.py", line 108, in <module>
    main()
  File "src/tools/train.py", line 86, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/cache/user-job-dir/codes/mmdetection/src/mmdet/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/cache/user-job-dir/codes/mmdetection/src/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'normal'
How can i solve this problem?Thanks

**Comment by cizhenshi** [comment]
We changed the default dataloader and added some new parameters. Just copying the configuration file is not enough. You also need to change the corresponding dataloader.

**Comment by EwardJohn** [comment]
Thanks for your reply,I am a new guy for OB,you mean I need change dataloader of torch.utils.data?
Best wishes!

**Comment by cizhenshi** [comment]
Not the torch.utils.dataloader. Did you use a custom dataset? In the ./mmdet/datasets/coco.py or any other dataset? My configs needs to be used with ./mmdet/datasets/coco_r2.py.

**Comment by EwardJohn** [comment]
I use the dataset like coco,in the ./mmdet/datasets/coco.py.Which
dataloader file should i change if i use coco dataset Or the config file must match coco_r2 ?Thanks !

cizhenshi <notifications@github.com> 于2020年4月20日周一 下午3:13写道：

**Comment by cizhenshi** [comment]
If you want to use the other settings in the configs except dataset, you need to change the 171-line dataset_type = 'CocopairDataset_r2' in the config file.  You can refer to some of the default configuration files in mmdetection.

**Comment by EwardJohn** [comment]
OK,i figured it out.
Best wishes!

cizhenshi <notifications@github.com> 于2020年4月20日周一 下午4:20写道：
