### ISSUE TITLE
error as running train_model2.sh 

### ISSUE THREAD

**Issue by robingong** [cizhenshi/TianchiGuangdong2019_2th#14]
When I run train_model2.sh , it has an error. Could you give me some tips? thanks!
GPU: Titan V; memory:32G
Run: ./train_model2.sh 1 

Error:
Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/mmcv/runner/runner.py", line 384, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/mmcv/runner/runner.py", line 283, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 376, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/core/fp16/decorators.py", line 75, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/models/detectors/cascade_rcnn_pair.py", line 556, in forward_train
    proposals=proposals)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/models/detectors/cascade_rcnn_pair.py", line 268, in forward_train_single
    *rpn_loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/models/anchor_heads/rpn_head.py", line 51, in loss
    gt_bboxes_ignore=gt_bboxes_ignore)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/core/fp16/decorators.py", line 152, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/models/anchor_heads/anchor_head.py", line 179, in loss
    sampling=self.sampling)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/core/anchor/anchor_target.py", line 116, in anchor_target_single
    anchors, gt_bboxes, gt_bboxes_ignore, None, cfg)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/core/bbox/assign_sampling.py", line 30, in assign_and_sample
    gt_labels)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/core/bbox/assigners/max_iou_assigner.py", line 93, in assign
    overlaps = bbox_overlaps(gt_bboxes, bboxes)
  File "/opt/data/TianchiGuangdong2019_2th/src/mmdet/core/bbox/geometry.py", line 51, in bbox_overlaps
    wh = (rb - lt + 1).clamp(min=0)  # [rows, cols, 2]
RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

Traceback (most recent call last):
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/nanhui2/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/nanhui2/anaconda3/envs/open-mmlab2/bin/python', '-u', './tools/train.py', '--local_rank=0', '../config/cascade_x101_20e.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by cizhenshi** [comment]
In order to avoid the insufficient GPU memory caused by too many proposals in the allocation stage, we migrated the part of proposal allocation to the CPU. This error might point to not enough RAM on your machine. Do you know the size of the data you are trying to load and if so, would it theoretically fit in your RAM?

**Comment by robingong** [comment]
co

> In order to avoid the insufficient GPU memory caused by too many proposals in the allocation stage, we migrated the part of proposal allocation to the CPU. This error might point to not enough RAM on your machine. Do you know the size of the data you are trying to load and if so, would it theoretically fit in your RAM?

commonly, 7.xG RAM was used as trainning. Let me log "the size of the data " when error.

**Comment by cizhenshi** [comment]
I used 32G RAM for my training, and I'm not sure how much memory it need as least.

**Comment by robingong** [comment]
> I used 32G RAM for my training, and I'm not sure how much memory it need as least.

yes, I used 32G RAM too, but the above error occurs...

**Comment by Kyle-fang** [comment]
所以该怎么解决呢
